### ISSUE TITLE
Передача дополнительных параметров при загрузке изображения

### ISSUE THREAD

**Issue by zabavnikov** [codex-editor/image#3]
Здравствуйте. :)

Добавьте, пожалуйста, возможность передачи дополнительных параметров при загрузке изображения.

Спасибо. :)

**Comment by neSpecc** [comment]
Привет. Опишите, пожалуйста, пример вашего кейса: какие параметры вы бы хотели передать. Можем добавить поле в конфиг плагина.

**Comment by zabavnikov** [comment]
Есть UploadController, он принимает файл, а так же доп. параметры: module_name (обязательный, может содержать - pages, stories. Используется при формирование пути для загрузки изображения.), а еще есть user_id (необязательный, используется в зависимости от ситуации).

**Comment by zabavnikov** [comment]
Было бы классно еще и дополнительные заголовки передавать, потому что например в Laravel при загрузке картинки вылетает ошибка, если не передать дополнительный заголовок с csrf токеном.
